/**
 * V2 GA Outreach Packet Generator
 *
 * Generates .eml (email) and .ics (calendar invite) files for GA readiness
 * stakeholder outreach. Does NOT send emails — only creates files for review.
 *
 * Usage:
 *   npx tsx scripts/ga/generate_outreach_packets.ts
 *   npx tsx scripts/ga/generate_outreach_packets.ts --config config/contacts/ga_contacts.example.json
 *   npx tsx scripts/ga/generate_outreach_packets.ts --dry-run
 *
 * Output: outreach/generated/<timestamp>/
 *
 * @module scripts/ga
 */

import * as fs from 'fs';
import * as path from 'path';

// ── Types ──────────────────────────────────────────────────────

interface Stakeholder {
  name: string;
  email: string;
  role: string;
  calendarPreference?: string;
}

interface OrgConfig {
  name: string;
  replyTo: string;
  projectUrl: string;
}

interface MeetingConfig {
  title: string;
  durationMinutes: number;
  location: string;
  defaultDate: string;
  timezone: string;
}

interface ContactsConfig {
  stakeholders: Stakeholder[];
  organization: OrgConfig;
  meeting: MeetingConfig;
}

// ── Template Generators ────────────────────────────────────────

function generateEml(stakeholder: Stakeholder, org: OrgConfig, meeting: MeetingConfig): string {
  const date = new Date().toUTCString();
  const boundary = `----=_Part_${Date.now()}`;

  const body = `Dear ${stakeholder.name},

I am writing to invite you to the CareConnect V2 Intake GA Readiness Review.

MEETING DETAILS:
  Title:    ${meeting.title}
  Date:     ${new Date(meeting.defaultDate).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
  Time:     ${new Date(meeting.defaultDate).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })} (${meeting.timezone})
  Duration: ${meeting.durationMinutes} minutes
  Location: ${meeting.location}

YOUR ROLE: ${formatRole(stakeholder.role)}

AGENDA:
  1. V2 Intake Scoring Engine overview (deterministic, 4-dimension)
  2. Clinical calibration results review
  3. DV-safe panic button demonstration
  4. GO/NO-GO gate criteria walkthrough
  5. Timeline and deployment plan

PREPARATION:
  - Review the attached evidence pack summary
  - Prepare any clinical calibration concerns
  - Note any DV safety requirements for your population

PROJECT: ${org.projectUrl}

This is an automated outreach message generated by the GA readiness toolkit.
Please confirm your attendance by replying to this email.

Best regards,
${org.name} Engineering Team
${org.replyTo}
`;

  return `MIME-Version: 1.0
From: ${org.name} Engineering <${org.replyTo}>
To: ${stakeholder.name} <${stakeholder.email}>
Subject: [Action Required] ${meeting.title} — ${formatRole(stakeholder.role)} Review
Date: ${date}
Reply-To: ${org.replyTo}
Content-Type: multipart/mixed; boundary="${boundary}"
X-Mailer: CareConnect-GA-Outreach-Generator
X-Priority: 3

--${boundary}
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: 7bit

${body}
--${boundary}--
`;
}

function generateIcs(stakeholder: Stakeholder, org: OrgConfig, meeting: MeetingConfig): string {
  const start = new Date(meeting.defaultDate);
  const end = new Date(start.getTime() + meeting.durationMinutes * 60 * 1000);
  const uid = `ga-review-${Date.now()}-${stakeholder.email.replace(/[^a-z0-9]/gi, '')}`;

  const formatIcsDate = (d: Date): string => {
    return d.toISOString().replace(/[-:]/g, '').replace(/\.\d{3}/, '');
  };

  return `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//CareConnect//GA Outreach Generator//EN
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VEVENT
UID:${uid}
DTSTART:${formatIcsDate(start)}
DTEND:${formatIcsDate(end)}
SUMMARY:${meeting.title}
DESCRIPTION:GA Readiness Review for CareConnect V2 Intake.\\n\\nRole: ${formatRole(stakeholder.role)}\\n\\nAgenda:\\n1. Scoring Engine Overview\\n2. Calibration Results\\n3. DV-Safe Demo\\n4. GO/NO-GO Criteria\\n5. Deployment Plan\\n\\nProject: ${org.projectUrl}
LOCATION:${meeting.location}
ORGANIZER;CN=${org.name}:mailto:${org.replyTo}
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;CN=${stakeholder.name}:mailto:${stakeholder.email}
STATUS:TENTATIVE
TRANSP:OPAQUE
SEQUENCE:0
BEGIN:VALARM
TRIGGER:-PT30M
ACTION:DISPLAY
DESCRIPTION:${meeting.title} starts in 30 minutes
END:VALARM
END:VEVENT
END:VCALENDAR
`;
}

function formatRole(role: string): string {
  return role.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}

function generateManifest(stakeholders: Stakeholder[], outputDir: string): string {
  const lines = [
    '# GA Outreach Packet Manifest',
    '',
    `Generated: ${new Date().toISOString()}`,
    `Output Directory: ${outputDir}`,
    '',
    '## Stakeholders',
    '',
    '| Name | Role | Email File | Calendar File |',
    '|------|------|-----------|---------------|',
  ];

  for (const s of stakeholders) {
    const slug = s.email.replace(/[^a-z0-9]/gi, '_');
    lines.push(`| ${s.name} | ${formatRole(s.role)} | ${slug}.eml | ${slug}.ics |`);
  }

  lines.push('');
  lines.push('## Next Steps');
  lines.push('');
  lines.push('1. Review each .eml file for accuracy');
  lines.push('2. Import .ics files into calendar application');
  lines.push('3. Send emails through your mail client (copy/paste or import .eml)');
  lines.push('4. Track confirmations in this manifest');
  lines.push('');
  lines.push('> **IMPORTANT**: These files are generated — review before sending.');

  return lines.join('\n');
}

// ── Main ───────────────────────────────────────────────────────

function main(): void {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');

  // Find config
  let configPath = 'config/contacts/ga_contacts.example.json';
  const configIdx = args.indexOf('--config');
  if (configIdx >= 0 && args[configIdx + 1]) {
    configPath = args[configIdx + 1];
  }

  // Try real config first, fall back to example
  const realConfigPath = configPath.replace('.example', '');
  if (fs.existsSync(realConfigPath)) {
    configPath = realConfigPath;
  }

  if (!fs.existsSync(configPath)) {
    console.error(`Config not found: ${configPath}`);
    console.error('Copy config/contacts/ga_contacts.example.json to ga_contacts.json and fill in real contacts.');
    process.exit(1);
  }

  console.log(`Loading config: ${configPath}`);
  const config: ContactsConfig = JSON.parse(fs.readFileSync(configPath, 'utf-8'));

  if (!config.stakeholders || config.stakeholders.length === 0) {
    console.error('No stakeholders defined in config.');
    process.exit(1);
  }

  // Output directory
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const outputDir = path.join('outreach', 'generated', timestamp);

  console.log(`\nStakeholders: ${config.stakeholders.length}`);
  console.log(`Output:       ${outputDir}/`);
  console.log(`Dry run:      ${dryRun}\n`);

  if (dryRun) {
    console.log('[DRY RUN] Would generate:');
    for (const s of config.stakeholders) {
      const slug = s.email.replace(/[^a-z0-9]/gi, '_');
      console.log(`  ${slug}.eml  — Email to ${s.name} (${s.role})`);
      console.log(`  ${slug}.ics  — Calendar invite for ${s.name}`);
    }
    console.log(`  MANIFEST.md — Packet manifest`);
    console.log('\nNo files written.');
    return;
  }

  // Create output directory
  fs.mkdirSync(outputDir, { recursive: true });

  // Generate files
  let count = 0;
  for (const stakeholder of config.stakeholders) {
    const slug = stakeholder.email.replace(/[^a-z0-9]/gi, '_');

    // .eml
    const emlContent = generateEml(stakeholder, config.organization, config.meeting);
    const emlPath = path.join(outputDir, `${slug}.eml`);
    fs.writeFileSync(emlPath, emlContent, 'utf-8');
    console.log(`  [+] ${emlPath}`);

    // .ics
    const icsContent = generateIcs(stakeholder, config.organization, config.meeting);
    const icsPath = path.join(outputDir, `${slug}.ics`);
    fs.writeFileSync(icsPath, icsContent, 'utf-8');
    console.log(`  [+] ${icsPath}`);

    count++;
  }

  // Manifest
  const manifest = generateManifest(config.stakeholders, outputDir);
  const manifestPath = path.join(outputDir, 'MANIFEST.md');
  fs.writeFileSync(manifestPath, manifest, 'utf-8');
  console.log(`  [+] ${manifestPath}`);

  console.log(`\nGenerated ${count * 2 + 1} files for ${count} stakeholders.`);
  console.log('Review files before sending. These are NOT automatically sent.');
}

main();
