import { Router, Request, Response } from 'express';
import { Document, Packer, Paragraph, TextRun, AlignmentType, HeadingLevel } from 'docx';

const router = Router();

/**
 * Export GoFundMe draft as Word document
 * POST /api/export/word/:clientId
 * Body: { title, goal, category, location, beneficiary, story, summary }
 */
router.post('/word/:clientId', async (req: Request, res: Response) => {
  try {
    const { clientId } = req.params;
    const {
      title = '',
      goal = '',
      category = '',
      location = '',
      beneficiary = '',
      story = '',
      summary = ''
    } = req.body;

    // Create document
    const doc = new Document({
      sections: [
        {
          children: [
            // Title
            new Paragraph({
              text: 'GoFundMe Campaign Draft',
              heading: HeadingLevel.HEADING_1,
              alignment: AlignmentType.CENTER,
              spacing: { after: 400 }
            }),

            // Campaign Title
            new Paragraph({
              text: 'Campaign Title',
              heading: HeadingLevel.HEADING_2,
              spacing: { before: 300, after: 200 }
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: title || '[Not provided]',
                  bold: false
                })
              ],
              spacing: { after: 300 }
            }),

            // Fundraising Goal
            new Paragraph({
              text: 'Fundraising Goal',
              heading: HeadingLevel.HEADING_2,
              spacing: { before: 300, after: 200 }
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: goal ? `$${goal}` : '[Not provided]',
                  bold: false
                })
              ],
              spacing: { after: 300 }
            }),

            // Category
            new Paragraph({
              text: 'Category',
              heading: HeadingLevel.HEADING_2,
              spacing: { before: 300, after: 200 }
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: category || '[Not provided]',
                  bold: false
                })
              ],
              spacing: { after: 300 }
            }),

            // Location
            new Paragraph({
              text: 'Location',
              heading: HeadingLevel.HEADING_2,
              spacing: { before: 300, after: 200 }
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: location || '[Not provided]',
                  bold: false
                })
              ],
              spacing: { after: 300 }
            }),

            // Beneficiary
            new Paragraph({
              text: 'Beneficiary',
              heading: HeadingLevel.HEADING_2,
              spacing: { before: 300, after: 200 }
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: beneficiary || '[Not provided]',
                  bold: false
                })
              ],
              spacing: { after: 300 }
            }),

            // Summary
            new Paragraph({
              text: 'Short Summary (150 characters)',
              heading: HeadingLevel.HEADING_2,
              spacing: { before: 300, after: 200 }
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: summary || '[Not provided]',
                  bold: false
                })
              ],
              spacing: { after: 300 }
            }),

            // Full Story
            new Paragraph({
              text: 'Full Campaign Story',
              heading: HeadingLevel.HEADING_2,
              spacing: { before: 300, after: 200 }
            }),
            ...story.split('\n').map((line: string) => 
              new Paragraph({
                children: [
                  new TextRun({
                    text: line || ' ',
                    bold: false
                  })
                ],
                spacing: { after: 100 }
              })
            ),

            // Footer
            new Paragraph({
              text: '',
              spacing: { before: 600 }
            }),
            new Paragraph({
              text: '---',
              alignment: AlignmentType.CENTER,
              spacing: { before: 200, after: 200 }
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: 'Generated by CareConnect on ' + new Date().toLocaleDateString(),
                  italics: true,
                  size: 20
                })
              ],
              alignment: AlignmentType.CENTER,
              spacing: { after: 100 }
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: 'For support: workflown8n@gmail.com',
                  italics: true,
                  size: 20
                })
              ],
              alignment: AlignmentType.CENTER
            })
          ]
        }
      ]
    });

    // Generate buffer
    const buffer = await Packer.toBuffer(doc);

    // Send as download
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    res.setHeader('Content-Disposition', `attachment; filename="gofundme-draft-${clientId}.docx"`);
    res.send(buffer);
  } catch (error: any) {
    console.error('[Export] Word generation error:', error);
    return res.status(500).json({
      success: false,
      error: 'Failed to generate Word document',
      message: error.message
    });
  }
});

export default router;
